### ISSUE TITLE
php 增加扩展

### ISSUE THREAD

**Issue by secretgao** [AugusLarry/docker-mmnpr#1]
大佬您好 看了你的docker-compose.yml 文件 如果 我想给php 增加扩展 我应该在文件中怎么写啊 还是说 我直接还是源码编译生成.so文件之后 复制到 php运行的容器中啊？

**Comment by AugusLarry** [comment]
php目录中有一个Dockerfile文件,改这个文件然后重新build就行了

**Comment by secretgao** [comment]
那就是在 Dockerfile 这个文件中 写命令 
   RUN pecl install xdebug \
	&& pecl install redis \
	&& docker-php-ext-enable redis xdebug

类似这样  ？

**Comment by AugusLarry** [comment]
如果不是pecl的扩展,写在docker-php-ext-install gd mysqli pdo_mysql zip opcache这个后面，不然安装不了
